### PR TITLE
Oct2016

### PR DESCRIPTION
**Pull request by vad710**
This PR contains various changes:
- Additional Analyzer (looks for ForEach loops in Update methods)
- Removed Analyzers that did not have an obvious workaround within Unity (or were not perf related)
- Fixed various unit tests
- Added a CLI tool for running in CI

The changes are still in progress and another PR will be submitted once more functionality is finalized - but the current state should be ready for initial feedback

### CODE REVIEW

**Comment by meng-hui** [comment]
Thanks for the PR. I'll probably spend this or next weekend looking through it.

Some initial thoughts
- I think it would be good to add more analyzers instead of removing or renaming them. Users can then configure which they would like using Visual Studio.
- I found the analyzers I did for Coroutine and OnGUI usage useful because they cause GC allocations and eventually causing a GC.Collect pause

**Comment by vad710** [comment]
I understand that there are draw backs to those calls, I am just weary of inspections that do not have a specific work-around as that could cause users get into the habit of ignoring inspections. Perhaps they could be categorized a bit differently?

**Comment by meng-hui** [comment]
Yeah, categorizing them as Info might be better, since they do not show by default in VS.

**Comment by vad710** [comment]
I added the Analyzers back in and change the default severity to Info. There are some unit tests that are failing, I am working on that now.

**Comment by vad710** [comment]
All unit tests are currently passing

**Comment by vad710** [comment]
Hi @meng-hui 
I've not heard from you for a little while. Please let me know if you have interest in continuing to maintain this project or if I should just focus on my fork.

This PR closes #1 , #2 , #3 and #4 

Thanks!

**Comment by meng-hui** [comment]
Thanks @vad710, for fixing the issues, adding features and the refactoring. Is this PR ready?

If you have immediate needs, I think you should focus on your fork.

**Comment by vad710** [comment]
The PR is ready for you to review. I will continue making updates to my for in the meantime.

Thanks!

**Pull request merged**
